# no borders when there is only one window on the workspace
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule = border_size 0, match:float false, match:workspace w[tv1]
windowrule = rounding 0, match:float false, match:workspace w[tv1]
windowrule = border_size 0, match:float false, match:workspace f[1]
windowrule = rounding 0, match:float false, match:workspace f[1]
